package inventory

import (
	"errors"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/vikki8/systemcd/internal/host"
	"github.com/vikki8/systemcd/internal/resource"
)

// GenerateOptions configures turning a scan into manifests.
type GenerateOptions struct {
	Host host.Host
	// Dir is the repository directory to write into. Manifests land in
	// <Dir>/manifests and file payloads in <Dir>/files, matching the layout
	// the loader already expects.
	Dir string
	// Categories restricts what is generated. Empty means every category
	// that can be expressed as a resource.
	Categories []Category
	// MaxFileBytes skips payloads larger than this, since a repository is not
	// a place for binaries or logs that ended up under /etc.
	MaxFileBytes int64
	// Targets, when set, scopes every generated document to these labels so a
	// discovered configuration does not land on the whole fleet by accident.
	Targets map[string]string
}

// DefaultMaxFileBytes is a deliberately conservative payload ceiling.
const DefaultMaxFileBytes = 512 * 1024

// GenerateResult reports what was written.
type GenerateResult struct {
	ManifestPath string
	FilePaths    []string
	Documents    int
	Skipped      []string
}

// Generate turns unmanaged inventory items into manifests plus extracted file
// payloads, ready to commit.
//
// The output is deliberately a starting point, not a finished repository: it
// captures what is on the machine so the first `plan` after adoption is empty
// and every later change is a reviewable diff. Turning discovered reality into
// intended configuration is the operator's judgement, not the tool's.
func Generate(rep *Report, opts GenerateOptions) (*GenerateResult, error) {
	if opts.Host == nil {
		return nil, errors.New("inventory: no host provided")
	}
	if opts.Dir == "" {
		return nil, errors.New("inventory: no output directory provided")
	}
	if opts.MaxFileBytes == 0 {
		opts.MaxFileBytes = DefaultMaxFileBytes
	}

	out := &GenerateResult{}
	var docs []string
	usedNames := map[string]bool{}

	for _, item := range rep.Unmanaged() {
		if len(opts.Categories) > 0 && !containsCategory(opts.Categories, item.Category) {
			continue
		}
		doc, extra, err := generateOne(item, opts, usedNames)
		if err != nil {
			out.Skipped = append(out.Skipped, fmt.Sprintf("%s: %v", item.Claim, err))
			continue
		}
		if doc == "" {
			continue
		}
		docs = append(docs, doc)
		out.FilePaths = append(out.FilePaths, extra...)
	}

	if len(docs) == 0 {
		return out, nil
	}

	header := "# Generated by `systemcd inventory --generate`.\n" +
		"#\n" +
		"# This is a snapshot of what is already on " + rep.Hostname + ", not a\n" +
		"# statement of what should be. Review it, delete what should not be\n" +
		"# managed, then `systemcd adopt` to take ownership without changing\n" +
		"# anything, and edit from there.\n"

	manifestPath := path.Join(opts.Dir, "manifests", "discovered.yaml")
	body := header + strings.Join(docs, "---\n")
	if err := opts.Host.WriteFile(manifestPath, []byte(body), 0o644); err != nil {
		return nil, err
	}
	out.ManifestPath = manifestPath
	out.Documents = len(docs)
	return out, nil
}

func containsCategory(list []Category, c Category) bool {
	for _, item := range list {
		if item == c {
			return true
		}
	}
	return false
}

func generateOne(item Item, opts GenerateOptions, used map[string]bool) (string, []string, error) {
	claim := resource.ParseClaim(item.Claim)

	switch claim.Kind {
	case resource.ClaimPath:
		return generateFile(item, claim.Key, opts, used)
	case resource.ClaimUnit:
		name := uniqueName(strings.TrimSuffix(claim.Key, ".service"), used)
		return renderDoc("Service", name, opts.Targets, map[string]string{
			"unit":    claim.Key,
			"enabled": "true",
			"state":   "started",
		}), nil, nil
	case resource.ClaimPackage:
		name := uniqueName(claim.Key, used)
		return renderDoc("Package", name, opts.Targets, map[string]string{"name": claim.Key}), nil, nil
	case resource.ClaimUser:
		name := uniqueName(claim.Key, used)
		return renderDoc("User", name, opts.Targets, map[string]string{"user": claim.Key}), nil, nil
	default:
		return "", nil, nil
	}
}

func generateFile(item Item, filePath string, opts GenerateOptions, used map[string]bool) (string, []string, error) {
	info, err := opts.Host.Stat(filePath)
	if err != nil {
		return "", nil, err
	}
	if info.Size > opts.MaxFileBytes {
		return "", nil, fmt.Errorf("file is %d bytes, above the %d byte limit for generated payloads", info.Size, opts.MaxFileBytes)
	}
	data, err := opts.Host.ReadFile(filePath)
	if err != nil {
		return "", nil, err
	}
	if !looksLikeText(data) {
		return "", nil, errors.New("file does not look like text, so it does not belong in a manifest repository")
	}

	name := uniqueName(strings.TrimPrefix(filePath, "/"), used)
	payload := path.Join("files", name)
	if err := opts.Host.WriteFile(path.Join(opts.Dir, payload), data, 0o644); err != nil {
		return "", nil, err
	}

	fields := map[string]string{
		"path":   filePath,
		"source": payload,
		"mode":   "\"0" + strconv.FormatUint(uint64(info.Mode.Perm()), 8) + "\"",
	}
	if owner, err := opts.Host.LookupUserName(info.UID); err == nil {
		fields["owner"] = owner
	}
	if group, err := opts.Host.LookupGroupName(info.GID); err == nil {
		fields["group"] = group
	}

	kind := "File"
	if strings.HasPrefix(filePath, "/etc/systemd/system/") {
		// A unit file is better expressed as the kind that knows to run
		// daemon-reload after writing it.
		kind = "SystemdUnit"
		fields = map[string]string{
			"unit":   path.Base(filePath),
			"source": payload,
		}
	}
	return renderDoc(kind, name, opts.Targets, fields), []string{payload}, nil
}

// renderDoc emits one manifest document. Values are written verbatim, so
// callers quote anything that YAML would otherwise reinterpret (an octal mode
// being the obvious trap).
func renderDoc(kind, name string, targets map[string]string, fields map[string]string) string {
	var b strings.Builder
	b.WriteString("apiVersion: systemcd.dev/v1\n")
	fmt.Fprintf(&b, "kind: %s\n", kind)
	b.WriteString("metadata:\n")
	fmt.Fprintf(&b, "  name: %s\n", name)
	if len(targets) > 0 {
		b.WriteString("  targets:\n    labels:\n")
		for _, k := range sortedKeys(targets) {
			fmt.Fprintf(&b, "      %s: %s\n", k, targets[k])
		}
	}
	if len(fields) > 0 {
		b.WriteString("spec:\n")
		for _, k := range sortedKeys(fields) {
			fmt.Fprintf(&b, "  %s: %s\n", k, fields[k])
		}
	}
	return b.String()
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

var unsafeName = regexp.MustCompile(`[^a-z0-9-]+`)

// uniqueName turns a path or package name into a stable, readable resource
// name that survives being used as a filename.
func uniqueName(raw string, used map[string]bool) string {
	name := unsafeName.ReplaceAllString(strings.ToLower(raw), "-")
	name = strings.Trim(name, "-")
	if name == "" {
		name = "resource"
	}
	if len(name) > 60 {
		name = name[len(name)-60:]
		name = strings.TrimLeft(name, "-")
	}
	candidate := name
	for i := 2; used[candidate]; i++ {
		candidate = name + "-" + strconv.Itoa(i)
	}
	used[candidate] = true
	return candidate
}

// looksLikeText rejects binaries by looking for NUL bytes, which is the same
// heuristic git uses and is right often enough.
func looksLikeText(data []byte) bool {
	limit := len(data)
	if limit > 8000 {
		limit = 8000
	}
	for _, b := range data[:limit] {
		if b == 0 {
			return false
		}
	}
	return true
}
