package inventory

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"path"
	"regexp"
	"strconv"
	"strings"

	"github.com/vikki8/systemcd/internal/host"
	"github.com/vikki8/systemcd/internal/resource"
	"gopkg.in/yaml.v3"
)

// GenerateOptions configures turning a scan into manifests.
type GenerateOptions struct {
	Host host.Host
	// Dir is the repository directory to write into. Manifests land in
	// <Dir>/manifests and file payloads in <Dir>/files, matching the layout
	// the loader already expects.
	Dir string
	// Categories restricts what is generated. Empty means every category
	// that can be expressed as a resource.
	Categories []Category
	// MaxFileBytes skips payloads larger than this, since a repository is not
	// a place for binaries or logs that ended up under /etc.
	MaxFileBytes int64
	// Targets, when set, scopes every generated document to these labels so a
	// discovered configuration does not land on the whole fleet by accident.
	Targets map[string]string
}

// DefaultMaxFileBytes is a deliberately conservative payload ceiling.
const DefaultMaxFileBytes = 512 * 1024

// GenerateResult reports what was written.
type GenerateResult struct {
	ManifestPath string
	FilePaths    []string
	Documents    int
	Skipped      []string
}

// Generate turns unmanaged inventory items into manifests plus extracted file
// payloads, ready to commit.
//
// The output is deliberately a starting point, not a finished repository: it
// captures what is on the machine so the first `plan` after adoption is empty
// and every later change is a reviewable diff. Turning discovered reality into
// intended configuration is the operator's judgement, not the tool's.
func Generate(rep *Report, opts GenerateOptions) (*GenerateResult, error) {
	if opts.Host == nil {
		return nil, errors.New("inventory: no host provided")
	}
	if opts.Dir == "" {
		return nil, errors.New("inventory: no output directory provided")
	}
	if opts.MaxFileBytes == 0 {
		opts.MaxFileBytes = DefaultMaxFileBytes
	}

	// An earlier snapshot may already have been reviewed and edited; it is
	// not this run's to replace.
	manifestPath := path.Join(opts.Dir, "manifests", "discovered.yaml")
	if _, err := opts.Host.Stat(manifestPath); err == nil {
		return nil, fmt.Errorf("inventory: %s already exists; move it aside or generate into another directory", manifestPath)
	} else if !errors.Is(err, host.ErrNotExist) {
		return nil, err
	}

	out := &GenerateResult{}
	// A snapshot of an incomplete scan is incomplete too, and this is the
	// only place a generate run reports.
	for _, note := range rep.Skipped {
		out.Skipped = append(out.Skipped, "scan incomplete: "+note)
	}
	var docs []string
	usedNames := map[string]bool{}
	// Payloads already under files/ are named around, never overwritten.
	if existing, err := opts.Host.ReadDir(path.Join(opts.Dir, "files")); err == nil {
		for _, name := range existing {
			usedNames[name] = true
		}
	}
	generated := map[string]bool{}

	for _, item := range rep.Unmanaged() {
		if len(opts.Categories) > 0 && !containsCategory(opts.Categories, item.Category) {
			continue
		}
		// One path is often found by several scans (a local unit is also
		// unpackaged config); two resources claiming it would not load.
		if generated[item.Claim] {
			continue
		}
		generated[item.Claim] = true
		doc, extra, err := generateOne(item, opts, usedNames)
		if err != nil {
			out.Skipped = append(out.Skipped, fmt.Sprintf("%s: %v", item.Claim, err))
			continue
		}
		if doc == "" {
			continue
		}
		docs = append(docs, doc)
		out.FilePaths = append(out.FilePaths, extra...)
	}

	if len(docs) == 0 {
		return out, nil
	}

	header := "# Generated by `systemcd inventory --generate`.\n" +
		"#\n" +
		"# This is a snapshot of what is already on " + rep.Hostname + ", not a\n" +
		"# statement of what should be. Review it, delete what should not be\n" +
		"# managed, then `systemcd adopt` to take ownership without changing\n" +
		"# anything, and edit from there.\n"

	body := header + strings.Join(docs, "---\n")
	if err := opts.Host.WriteFile(manifestPath, []byte(body), 0o644); err != nil {
		return nil, err
	}
	out.ManifestPath = manifestPath
	out.Documents = len(docs)
	return out, nil
}

func containsCategory(list []Category, c Category) bool {
	for _, item := range list {
		if item == c {
			return true
		}
	}
	return false
}

func generateOne(item Item, opts GenerateOptions, used map[string]bool) (string, []string, error) {
	claim := resource.ParseClaim(item.Claim)

	switch claim.Kind {
	case resource.ClaimPath:
		return generateFile(item, claim.Key, opts, used)
	case resource.ClaimUnit:
		name := uniqueName(strings.TrimSuffix(claim.Key, ".service"), used)
		doc, err := renderDoc("Service", name, opts.Targets, map[string]any{
			"unit":    claim.Key,
			"enabled": true,
			"state":   serviceState(opts, claim.Key),
		})
		return doc, nil, err
	case resource.ClaimPackage:
		name := uniqueName(claim.Key, used)
		doc, err := renderDoc("Package", name, opts.Targets, map[string]any{"name": claim.Key})
		return doc, nil, err
	case resource.ClaimUser:
		name := uniqueName(claim.Key, used)
		doc, err := renderDoc("User", name, opts.Targets, map[string]any{"user": claim.Key})
		return doc, nil, err
	default:
		return "", nil, nil
	}
}

// serviceState records whether a unit is running now. The scan only
// established that it is enabled; asserting `started` for a oneshot that ran
// at boot and exited would make the first plan after adoption start it.
func serviceState(opts GenerateOptions, unit string) string {
	res, err := opts.Host.Run(context.Background(), "systemctl", "is-active", unit)
	if err == nil && strings.TrimSpace(res.Stdout) == "active" {
		return "started"
	}
	return "unmanaged"
}

func generateFile(item Item, filePath string, opts GenerateOptions, used map[string]bool) (string, []string, error) {
	if skipPath(filePath) {
		return "", nil, errors.New("secrets and per-machine state are never copied into a repository")
	}
	info, err := opts.Host.Stat(filePath)
	if err != nil {
		return "", nil, err
	}
	if info.Target != "" {
		// Reading through the link would manage a copy of its target, with
		// the link's own 0777 as the mode.
		return "", nil, fmt.Errorf("is a symlink to %s, which a File resource cannot express", info.Target)
	}
	if info.IsDir {
		return "", nil, errors.New("is a directory")
	}
	if info.Mode&0o004 == 0 {
		return "", nil, fmt.Errorf("mode %04o is not world-readable, which usually means it holds a secret, so its contents are not copied into a repository", info.Mode.Perm())
	}
	if info.Size > opts.MaxFileBytes {
		return "", nil, fmt.Errorf("file is %d bytes, above the %d byte limit for generated payloads", info.Size, opts.MaxFileBytes)
	}
	data, err := opts.Host.ReadFile(filePath)
	if err != nil {
		return "", nil, err
	}
	if !looksLikeText(data) {
		return "", nil, errors.New("file does not look like text, so it does not belong in a manifest repository")
	}

	name := uniqueName(strings.TrimPrefix(filePath, "/"), used)
	payload := path.Join("files", name)

	spec := map[string]any{
		"path":   filePath,
		"source": payload,
		"mode":   fmt.Sprintf("%04o", info.Mode.Perm()),
	}
	if owner, err := opts.Host.LookupUserName(info.UID); err == nil {
		spec["owner"] = owner
	}
	if group, err := opts.Host.LookupGroupName(info.GID); err == nil {
		spec["group"] = group
	}

	kind := "File"
	dir, base := path.Split(filePath)
	// A unit file is better expressed as the kind that knows to run
	// daemon-reload after writing it, when that kind can reproduce it
	// exactly: SystemdUnit always writes mode 0644 and appends ".service" to
	// a name without a suffix. Drop-ins (foo.service.d/override.conf) keep
	// their directory.
	if strings.HasPrefix(filePath, "/etc/systemd/system/") && strings.Contains(base, ".") && info.Mode.Perm() == 0o644 {
		kind = "SystemdUnit"
		spec = map[string]any{
			"unit":   base,
			"source": payload,
		}
		if dir = strings.TrimSuffix(dir, "/"); dir != "/etc/systemd/system" {
			spec["directory"] = dir
		}
	}
	doc, err := renderDoc(kind, name, opts.Targets, spec)
	if err != nil {
		return "", nil, err
	}
	if err := opts.Host.WriteFile(path.Join(opts.Dir, payload), data, 0o644); err != nil {
		return "", nil, err
	}
	return doc, []string{payload}, nil
}

type generatedDoc struct {
	APIVersion string            `yaml:"apiVersion"`
	Kind       string            `yaml:"kind"`
	Metadata   generatedMetadata `yaml:"metadata"`
	Spec       map[string]any    `yaml:"spec,omitempty"`
}

type generatedMetadata struct {
	Name    string            `yaml:"name"`
	Targets *generatedTargets `yaml:"targets,omitempty"`
}

type generatedTargets struct {
	Labels map[string]string `yaml:"labels"`
}

// renderDoc emits one manifest document through the YAML encoder, so every
// value is quoted as it needs to be: an octal mode, a path containing " #" or
// ": ", or a label value such as "yes" all read back as the string they were.
func renderDoc(kind, name string, targets map[string]string, spec map[string]any) (string, error) {
	doc := generatedDoc{
		APIVersion: "systemcd.dev/v1",
		Kind:       kind,
		Metadata:   generatedMetadata{Name: name},
		Spec:       spec,
	}
	if len(targets) > 0 {
		doc.Metadata.Targets = &generatedTargets{Labels: targets}
	}
	var b bytes.Buffer
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return "", err
	}
	if err := enc.Close(); err != nil {
		return "", err
	}
	return b.String(), nil
}

var unsafeName = regexp.MustCompile(`[^a-z0-9-]+`)

// uniqueName turns a path or package name into a stable, readable resource
// name that survives being used as a filename.
func uniqueName(raw string, used map[string]bool) string {
	name := unsafeName.ReplaceAllString(strings.ToLower(raw), "-")
	name = strings.Trim(name, "-")
	if name == "" {
		name = "resource"
	}
	if len(name) > 60 {
		// Keep the distinctive end of a long path, starting on a whole
		// word: "etc-systemd-..." cut mid-word read as "c-systemd-...".
		cut := len(name) - 60
		if name[cut-1] != '-' {
			if i := strings.IndexByte(name[cut:], '-'); i >= 0 {
				cut += i
			}
		}
		name = strings.TrimLeft(name[cut:], "-")
	}
	candidate := name
	for i := 2; used[candidate]; i++ {
		candidate = name + "-" + strconv.Itoa(i)
	}
	used[candidate] = true
	return candidate
}

// looksLikeText rejects binaries by looking for NUL bytes, which is the same
// heuristic git uses and is right often enough.
func looksLikeText(data []byte) bool {
	limit := len(data)
	if limit > 8000 {
		limit = 8000
	}
	for _, b := range data[:limit] {
		if b == 0 {
			return false
		}
	}
	return true
}
